# This is a basic workflow to help you get started with Actions

name: docker variables workflow
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: git-actions-nginx

jobs:
  
  docker:
    
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: echo docker build -t ${{ env.DOCKER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME

      - name: docker login 
        run: echo docker login --username=$DOCKER_USERNAME --password ${{ secrets.DOCKER_PASSWORD }}

      - name: generate ASCII artwork
        run: cowsay -f dragon "I am DRAGON run for cover, ...." > dragon.txt
      
      - name: upload dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
  
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

