# This is a basic workflow to help you get started with Actions

name: docker variables workflow
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: git-actions-nginx

jobs:
  
  docker:
    
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        run: echo docker build -t ${{ env.DOCKER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME

      - name: docker login 
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: docker publish
        run: echo docker push $DOCKER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:lates
  
  deploy:
    if: github.ref == 'refs/heads/main'
    concurrency: 
      group: production
      cancel-in-progress: false
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        timeout-minutes: 1
        run: |
          echo docker run -d -p 8080:80 $DOCKER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME
          sleep 100

