name: workflow filtres and activities

on: 
 push: 
   branches: 
    - main
    - '!feature/*'

 pull_request: 
    types: 
      - opened
      - closed
    paths-ignore: 
      - README.md
    branches: 
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo this worflow/job/step is executed for even type - ${{ github.event_name}}

  